modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL"
showAsResourcePack=false

[[mods]]
modId = "examplemod"
displayName = "examplemod"
version = "1.0.0"
authors = "DeDiamondPro"
description = ""